Repository BuildOnViction/victionchain, pull requests merged in 2020-03, with the labels that each got.

#165 tomoxlending: auto topup collateral
  common/constants.go
  core/lending_pool_test.go
  core/types/lending_signing.go
  core/types/lending_transaction.go
  internal/ethapi/api.go
  tomox/tradingstate/statedb.go
  tomoxlending/lendingstate/common.go
  tomoxlending/lendingstate/lendingitem.go
  tomoxlending/lendingstate/trade.go
  tomoxlending/order_processor.go
  tomoxlending/tomoxlending.go
Labels: READY TO MERGE

#182 fix trading lending state
  core/blockchain.go
  core/lending_pool_test.go
  core/order_pool_test.go
  core/state_processor.go
  tomox/tradingstate/dump.go
  tomox/tradingstate/state_lendingbook.go
  tomox/tradingstate/state_orderList.go
  tomoxlending/lendingstate/dump.go
  tomoxlending/lendingstate/state_itemList.go
  tomoxlending/lendingstate/state_liquidationtime.go
  tomoxlending/order_processor.go
Labels: READY TO MERGE

#187 tomoxlending: check resigned relayer + locked fund
  core/block_validator.go
  tomox/order_processor.go
  tomoxlending/lendingstate/lendingcontract.go
  tomoxlending/order_processor.go
Labels: DO NOT MERGE

#198 tomoxlending: update getCollateralPrice
  tomoxlending/order_processor.go
Labels: awaiting_review
